In [1]:
#This allows us to access nupy using the np.prefix
import numpy as np

In [2]:
# a function that squares all the values in a sequence above using regular python loops
def squares(values):
    result = []
    for v in values:
        result.append(v * v)
    return result

In [3]:
# create 100,000 numbers using python range 
to_square = range(100000)
#time how long it takes to repeadely square them all
%timeit squares(to_square)

36.9 ms ± 1.33 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [4]:
# using Numpy and verctorized arrays the example can be reqwritten as follows
array_to_square = np.arange(0, 100000)
# and time using a vectorized operation
%timeit array_to_square ** 2

238 µs ± 2.99 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [5]:
# Numpy arrays
# A simple array
a1 = np.array([1, 2, 3, 4, 5])
a1

array([1, 2, 3, 4, 5])

In [6]:
# What is its type?
type(a1)

numpy.ndarray

In [7]:
# How many elements?
np.size(a1)

5

In [8]:
# any float in the sequence above
# it an array of floats
a2 = np.array([1, 2, 3, 4.0, 5.0])
a2

array([1., 2., 3., 4., 5.])

In [9]:
# array is all of one type 
a2.dtype

dtype('float64')

In [10]:
# short hand to repeat a sequence 10 time
a3 = np.array([0] * 10)
a3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
# convert a python range to numpy array
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# Creat a numpy array of 10 0.0s 
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
# Force it to be of int insead of float 64 
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
# make "a range" starting at 0 and with 10 values 
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
# 0 <= x < 10 increment by two 
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [16]:
# 10 >= x > 0, counting down
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [17]:
# evenly spaced #s between two intervals
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [18]:
# multiply numpy array by 2
a1 = np.arange(0, 10)
a1*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
# add two numpy arrays
a2 = np.arange(10, 20)
a1 + a2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [20]:
# create a two dimensional array
np.array([[1,2], [3,4]])

array([[1, 2],
       [3, 4]])

In [21]:
# create a 1x20 array and reshape it to a 5x4 array
m = np.arange(0, 20).reshape(5, 4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [22]:
# size of any dimeonsianal array is the # of elements 
np.size(m)

20

In [23]:
# can ask the size along a given axis ( 0 is row)
np.size(m, 0)

5

In [24]:
# To determine the number of columns in the two-dimeonsinals array, we can pass the value 1
np.size(m, 1)

4

In [25]:
# select 0-based elemnts 0 and 2
a1[0], a2[2]

(0, 12)

In [26]:
# select an elment in 2d array at row 1 coumn 2
m[1, 2]

6

In [27]:
# all items in row 1
m[1,]

array([4, 5, 6, 7])

In [28]:
# all items in column 2
m[:,2]

array([ 2,  6, 10, 14, 18])

In [29]:
# which items are less tahn 2
a = np.arange(5)
a < 2

array([ True,  True, False, False, False])

In [30]:
# this is commented as it will cause an exception.
# print (a<2 or a>3
# use logical operators
(a<2) | (a>3)

array([ True,  True, False, False,  True])

In [31]:
# create a function that is applied to all array elements
def exp (x):
    return x<3 or x>3 
#np.vectorize applies te method to all items in an array
np.vectorize(exp)(a)

array([ True,  True,  True, False,  True])

In [32]:
# boolean select items < 3
r = a<3
#applying the result of the expression to the [] operator
# selects jsut the array elements where there is a matching true
a[r]

array([0, 1, 2])

In [33]:
#np.sum treats True as 1 and False as 0
# so this is how many items are less than 3
np.sum( a < 3)

3

In [34]:
# This can be applied to across two arrays
a1 = np.arange(0, 5)
a2 = np.arange(5, 0 , -1)
a1 < a2

array([ True,  True,  True, False, False])

In [35]:
# get all items in the array from position 3
# up to position 8 (but not inclusive)
a1 = np.arange(1, 10)
a1[3:8]

array([4, 5, 6, 7, 8])

In [36]:
# every other item
a1[::2]

array([1, 3, 5, 7, 9])

In [37]:
# in reverse order
a1[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [38]:
# note that when in reverse, this does not include 
# the element specified in the second component of the slices
# that there is no 1 printed i nthis
a1[9:0:-1]

array([9, 8, 7, 6, 5, 4, 3, 2])

In [39]:
# all items from positon 5 onwards
a1[5:]

array([6, 7, 8, 9])

In [40]:
# two-dimensional arrays
m[:,1]

array([ 1,  5,  9, 13, 17])

In [41]:
# in all rows, but for columns in positions 
# 1 up to but not including 2
m[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

In [42]:
# in row positions 3 up to but not including 4, all columns
m[3:5,:]

array([[12, 13, 14, 15],
       [16, 17, 18, 19]])

In [43]:
#combined to pull out a sub matrix of the matrix
m[3:5,1:3]

array([[13, 14],
       [17, 18]])

In [44]:
# using a python array, we can select 
# non-contriguous rows or columns
m[[1,3,4],:]

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

Reshaping Arrays

In [45]:
# create a 9 element array (1x9)
a =np.arange(0,9)
# and reshape to a 3x3 2-d array
m = a.reshape(3,3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [46]:
# reshape in downwars dimensions
reshaped = m.reshape(9)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
# .ravel()  will generate array representing a flattened 2-d array 
raveled = m.ravel()
raveled

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [48]:
# it does  not alter the shape of the source
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [49]:
# but it will be a view into the source
# so items changhed in the result of the ravbel
# are changed in the original object
# reshape m to ana rray
reshaped = m.reshape(np.size(m))
# ravel into an array
raveled = m.ravel()
# change the values in either
reshaped[2] = 1000
raveled[5] = 2000
# and they show as changed in the original
m

array([[   0,    1, 1000],
       [   3,    4, 2000],
       [   6,    7,    8]])